After Applying this Hack ADAR1000 would not work on Windows machine.
That means the python script than must be run on RPI itself.


## Multiple libiio and Pluto failing to rx.

#Update libiio:
git clone https://www.github.com/analogdevicesinc/libiio
cd libiio
cmake .
make
sudo make install

# Update pyadi-iio
git clone https://www.github.com/analogdevicesinc/pyadi-iio
sudo python3 setup.py install

# Update pylibiio:
sudo pip3 install pylibiio==0.23.1

# and finallyâ€¦ this is probably not the right thing to do, but after installing pylibiio version 0.23.1, iio.version was still 0.21! Okay, check iio.__file__ , which pointed to /lib/python3.7/site-packages/iio.py. But pip3 install process noted that it was installed to dist-packages. So to check if Python defers back to dist-packages:
sudo mv /lib/python3.7/site-packages/iio.py /lib/python3.7/site-packages/iio_save.py

And everything works!! Oh, and the updating Libiio was because at one point I got:
AttributeError: /lib/arm-linux-gnueabihf/libiio.so.0: undefined symbol: iio_device_get_label

So a few things to sort out, but at least now we know the delta from a freshly burned Kuiper image, to one where the rx() method works.

In order to run both adar1000 and Pluto on raspberry Pi you need to do this additional step

Clone the adar1000-labels-fix branch of pyadi and replace adar1000.py file from the local library where we import adi to adar1000.py of cloned branch

sudo clone --branch adar1000-labels-fix https://github.com/analogdevicesinc/pyadi-iio
sudo cp /home/analog/cloned_gits/pyadi-iio/adi/adar1000.py /usr/local/lib/python3.7/dist-packages/adi/adar1000.py:


For ADAR1000, auto uri is static i.e. ip:analog. so if you changed the hostname of raspberry Pi to something it will not dynamically change and you have to provedi uri="ip:something" in adi.adar1000() 

